# Generated by Django 5.1.2 on 2024-11-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                default=0.0,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
